version: '3.1'
services:
  postgres:
    image: postgres
    volumes:
      - "/var/lib/postgresql/data"
      #- "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    environment:
      #- POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=platzi
    container_name: postgres